### ISSUE TITLE
Daily Activity count(s) in the Monthly view

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#2]
Using a copy of the 7.5.4 Eval/Demo db all looks fine. However, when run against our own 7.5.4 production system, the counts are off.  There are days where thare is a indication of "1" and there's no activities for that day. On other days there are "9" but really only "8".

Any ideas?

Ques: How does SData deal w/recurring activities? - Could this be the smoking gun?

**Comment by rjledger** [comment]
Still looking for a solution..

**Comment by jhershauer** [comment]
We'll be sure to validate the numbers. Keep in mind that this is just our development branch, and not released/supported yet.

As for recurring activities, no, we don't show recurrences. The SData feed doesn't pass them through that way.

**Comment by rjledger** [comment]
Jeff, On the Demo/Eval dbit looks just fine - it's on my production system where I'm seeing the issue - If you guys have any suggestions where I can look, I'll be MORE than glad to take the time and troubleshoot it and see just where it's falling down on me and feed all that back to you guys - How's that sound?

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by jhershauer** [comment]
Is your argos-sdk code up-to-date? Also, does this appear to be happening on days with both timed and timeless activities, or perhaps just with timeless activities?

**Comment by wskidmore** [comment]
I know that at one point it was showing a Timeless (all-day) activity on the previous day - ie: Timeless activity on Friday would show up in the count for Thursday. However, I believed this was fixed early last week. As it stands the query is:

```
UserId eq "{0}" and (
   (Activity.Timeless eq false and Activity.StartDate between @{1}@ and @{2}@) or 
   (Activity.Timeless eq true and Activity.StartDate between @{3}@ and @{4}@)
)
```

The difference between the `{1}{2}` dates and the `{3}{4}` dates is the inclusion of any UTC offsets for timeless.

Timeless activities are always set to 12:00:05 AM, UTC time. Whereas normal activities are after 12:00:00 AM _local_ time. 

Not sure if that helps, but might be something to look at.

**Comment by rjledger** [comment]
As of right now - up to date on the dev and production to the latest.
Still see right counts (I believe) in the dev db (Slx Eval Demo db) but incorrect in our production.

If I look at this month, the first day w/counts is correct. It looks fine for a week or so and then on a Sat.. I see a "1" and there's no activity(s) really there. The next day (Sun) also shows "1".. and nothing there... same for the remainder of the week thru Thurs (there were activities - but they had been "completed"). Friday shows a "8" count but only see "7" listed. The missing one is a recurring activity (meeting).

There is a mix of timed and timeless. I have the habit of using timeless w/rollover for maintaining a "running tasks list" which may get completed as timeless or sometimes I change them to timed and then complete them.

Does this help?

Additional.. just did the following:
A - refreshed/reloaded the display/browser (ended up on login)
B - Logged in
C - Went to Calendar (default today list view) and it shows 14 items listed for today - FireBug says the payload only had 7 (which is correct).
D - Clicked on Week - it looks right (but missing the recurring activity)
E - Clicked on Month - bad counts on lots of days.. but it says there are "8" for today..

I captured (via FF) the payload.. and have a question about the value for dates - ex: if the startdate is 131254560000 - then is this a normal date serial value?
UPDATE: - rjl-> This is serial time since Jan 1, 1970 - Should have recognized that from my Unix (sys 5.4, bsd, etc) days ;-)

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
Yep.. I can see (vie Firebug) it's making the query as you show it.
Digging deeper...

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
Here is the "query" - I'm EDT local:

http://...my server.../sdata/slx/dynamic/-/useractivities?_includeContent=false&count=31&startIndex=1&select=Activity%2FStartDate%2CActivity%2FEndDate%2CActivity%2FTimeless&orderby=Activity.StartDate%20asc&where=UserId%20eq%20%22U6UJ9A00000A%22%20and%20%28%28Activity.Timeless%20eq%20false%20and%20Activity.StartDate%20between%20%402011-08-01T04%3A00%3A00Z%40%20and%20%402011-09-01T03%3A59%3A59Z%40%29%20or%20%28Activity.Timeless%20eq%20true%20and%20Activity.StartDate%20between%20%402011-08-01T00%3A00%3A00Z%40%20and%20%402011-08-31T23%3A59%3A59Z%40%29%29&format=json&_t=1313756123611

**Comment by rjledger** [comment]
Dug a bit deeper. Able to validate the Daily/Weekly lists are ok but the "count" is still off (using today's code from GitHub).

At a bit of a loss...

**Comment by rjledger** [comment]
I captured the query/payload and it is correct - what appears to be the issue is "something" is "off" in the actual processing of the results. I suspect it is in the views/Calendar/MonthView.js in the processFeed/highlightActivities function(s).

I'm more than willing to do a GoToMeeting and show you exactly what I'm seeing.
What do you guys think?

**Comment by jhershauer** [comment]
Ok, thanks RJ. We're in the process of doing some refactoring in this area. I'll let you know when we get to "feature complete", and we can see if you're still having issues.

Thanks,
Jeff

**Comment by rjledger** [comment]
Great! I'll keep an eye on GH especially for changes related to calendar.

Do you have a particular target timeframe for "feature complete"?

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
Tested it today (Thurs) and unfortunately no diff  - still getting "bad" counts".

**Comment by rjledger** [comment]
Just loaded up your latest (End of day Friday Aug 26) at 21:30 EDT - 
A - GREAT change to the Monthly view! Seeing the list of actual activities for the selected day just below the monthly cal is a GREAT improvement!
B - Still have the phantom counts showing up.. BUT because of "A" I know have more info for you... 1-> it happens the next day after the first recurring activity and it's gone on the very last day of the month ... 2-> It comes back on the day after the next recurring activity in the next month.. and is gone on the last day again.

**Comment by wskidmore** [comment]
Since mobile cannot schedule recurring activities nor multi-day activities yet I haven't been able to reproduce the error but I think this issue had to with how month views counts the totals:

In Month View when it is processing the activities to get the counts it is coded to handle multi-day activities (this was before we found out that it is not supported). It goes from the StartDate of the activity to the EndDate in 1 day increments adding a count to each day. There is also a lower and upper bound: Month/1/00:00:00 and Month/30 (31)/23:59:59 - and that's the key to your second point. Example:

Activity Phone Call - Bob Hope
StartDate - Aug 31
EndDate - Sep 2

Month View - Aug
It hits the StartDate Aug 31 and that is within bounds, so it gets 1 added to Aug 31. Next loop is Sep 1 and that is out of bounds so it stops.

Month View - Sept
Nothing gets added as the StartDate is last month (via the sdata query).

I don't have access to see what the EndDate of a recurring activity looks like (or maybe its null/false?) but it could be setting the EndDate to the last date of the recurrence, so that's why it keeps adding 1.

Now for Day/Week views, it _only_ looks at the StartDate. So using the example from above, it would only show 1 activity on Aug 31 with Sep 1, 2 blank. This is again because of the sdata query only pulling activities with a StartDate between 00:00 and 23:59 that day (or week).

I will bring this up at the next meeting and see where they would like to go, my guess is to change Month View to ignore EndDates and act like Day/Week until we can prioritize and schedule adding real recurring/multi-day support to all views. 

Thank you for keeping at it!

**Comment by rjledger** [comment]
OK.. just brought the changes into both my dev/test (that uses the OOTB SalesLogix Demo/eval db) and my production db.
RESULTS:
 Dev/test looks ok
 Production - no longer have the "extra" or phantom counts! DO see something interesting.. 
    Monthly shows NO count for Wed (31st) and weekly correctly shows "Meeting" type activity. Looks like the getLastDayofCurrentMonth is "off". It's subtracting one and I don't believe it should. In fact, I changed:
   this.currentDate.getDaysInMonth -1 
 to
   this.currentDate.getDaysInMonth
and now the activity count for the 31's shows up as well as the activity when I click on the 31st. Look at it closely and you will see what I mean.

One can attempt schedule activities that span several days via the Windows client and it does not show up correctly either. It does not obey the rules of "business hrs", etc...
The only thing that does span several days (and shows up right) is the "event type" activity which the mobile does not handle - unfortunately. It's useful for marking holidays, vacations, etc. You would have to get that from the EVENT entity - not the usercal... It would be a VERY nice add ;-)

FYI - Recurring Activities do show up because you really really not looking at the actual ACTIVITY entity - just the calendar info that reflects them. Of course you cannot edit "all occurrences" - just the "one"... and that is really OK as well. Personally.. I highly "dis-like" the way recurring activities are implemented in SalesLogix. It's a "mess" to understand the guts of them. I believe that recurring should be simply a "linked-list" of individual activities. A simple approach is to just add a field to the Activity (and History) entities to allow for "linking". It would make it easy to drop a single one out or add others in.... etc.. Then all that would be needed is a "tool" to convert the present recurring activity records into a "linked-list" ...Sorry.. did not mean to get off subject..

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by jhershauer** [comment]
Hi RJ - We'll definitely be looking at Events for the 8.0 release. We're also looking at fanning out recurring activity info in the DB for that release (managing it with a server-side process), making that info accessible via SData. Not 100% sure on that one, but it's definitely on the wish list if we can get to it.

Thanks,
Jeff

**Comment by rjledger** [comment]
Hi Jeff,
    Great news!
Really appreciate what you guys are doing. 
Thanks!
rjl

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
New Issue related to Month Cal:

Using the latest code (in our production system) just ran into an issue that turned up because of activity "Roll Over" which pushed 3 activities to today (Oct 1.. and it's a weekend day).

Every day of the month (Oct) is showing 3 activities in the "count" on the Monthly in addition to ant activities/events that were already scheduled. Oct 1 is OK.. but all the rest are incorrect.. Nov and Sept are OK.

**Comment by wskidmore** [comment]
Is it just the counts, or is it showing those 3 activities in the 'preview' below the calendar as well?

**Comment by rjledger** [comment]
Just the counts. Nothing shows below... except for the 1st - today - because they should show..

Interesting combination:
   A - "last day of the week"
   B - "first day of the month"

First time we have hit this combo... If you have a fix.. I can validate it rather quickly.
Thanks in advance - rjl

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by wskidmore** [comment]
I think this may fix it (I can't reproduce since I have no way of adding a 'roll over'), but just as a heads up the Extjs -> dojo conversion will be moved to the master branch soon -ish and the Calendar Views have been re-done (for performance and better event/activity styling).

**Comment by rjledger** [comment]
That fixed it!
Thanks!

Looking forward to the dojo changes.... One question... many of us have been deploying "package customs" and these have "Ext" based overrides in them. Will the dojo changes impact these?.. will we have a newer/better way to do "overrides"?

rjl

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by wskidmore** [comment]
I can't go into much detail at the moment as we are still converting argos-sdk/saleslogix, but most of it can easily be changed with a quick script to change the API calls to dojo equivalents, and if there isn't a dojo equiv we have been adding custom ones to keep the code change as small as possible. I would say 90% of the changes are just adding dojo.x() to the front since Ext was just extending base objects.

As for easier customizations, I know the toolbars have undergone some code changes to be customizable on a per view basis. I know there have been talks of other things to change to make it more open, so hopefully after dojo and secure role support we can go full throttle into everything else.

**Comment by jhershauer** [comment]
Hey RJ,
We're definitely rounding out the customization API, removing the need for so much overriding. You'll be able to use RegisterCustomization for toolbars and the home screen. It will be much more straight-forward. 

You COULD just do a straight ext-dojo conversion and leave your overrides, but I think it will be worth taking a few extra minutes to do some refactoring and go with the official customization API.

Thanks,
Jeff

**Comment by rjledger** [comment]
All sounding good Jeff.

Looking forward to getting my hands dirty on this as soon as possible. So far we have a dozen "modules" or so developed for both unique customer situations as well as some work we're doing on "spec" for basic reselling. Several of these we are field testing on our own production environment with great success so far. Just before or at Boot Camp time we will make some product announcements.

Ah.. just remembered one customization area that is a bit of a "pain".. When we are targeting where we want our "row" to land in OOTB Detail.js and Edit.js "object(s)". It has to do that there are no unique "id(s)" for these. So If I wanted my new "Project" row to show after an existing one.. and for some reason there was no unique way to locate where to assign the value to "at:" - I'm cooked.

Are you guys going to add in the "id" property to the ootb code for the rows?

.. again - thanks!

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----
