### ISSUE TITLE
V2.0 and up (master) - Month View hangs (the app) if Event scheduled for the last day

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#43]
.. specifically (how to repeat this problem 100% of the time) , if you schedule an Event for Oct 31st (Halloween) - it "hangs" the app when you switch to the month view for that month.. and the script appears to loop forever.

**Comment by wskidmore** [comment]
Master branch (v3.0) uses `valueOf()` on the dates which converts to milliseconds since the unix epoch -- and I don't experience any hanging on it. Note that 1.2/2.0 uses the datejs library which alters the Date prototype and is no longer maintained, for 3.0 date parsing is now handled by momentjs.

**Comment by rjledger** [comment]
So how do we fix the bug in 2?

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog
Direct Phone: +1  508.809.9513

**Comment by wskidmore** [comment]
I pushed up a commit to the 2.0 branch (should be above my comment):

https://github.com/SageSalesLogix/argos-saleslogix/commit/1b537ff1d880575583896483189b1986924fe7f8

**Comment by rjledger** [comment]
NICE!.. great to have a fast fix for it!
Really appreciate the work you guys do on this.
rjl

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog
Direct Phone: +1  508.809.9513

**Comment by rjledger** [comment]
Did the change to my 2.0 copy.. and tested.. still hanging..

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog
Direct Phone: +1  508.809.9513

**Comment by wskidmore** [comment]
Cleared cache? I use incognito mode in Chrome and have IIS to never cache .js/.css/.html/.aspx files.

Also found that WebStorm's new Live Editing in Chrome works very well.

**Comment by rjledger** [comment]
Nice tips.. and I found the same end of month "bug" is also in the 20_for_754 module ;-)

**Comment by wskidmore** [comment]
Thanks: https://github.com/SageSalesLogix/argos-saleslogix-20_for_754/commit/d37ffaece37d1e7a664cb55709a1389efc68b0bb

**Comment by rjledger** [comment]
You are welcome!.. I "fell" on it when building out a test env for 20 on 754. We're going to deploy a few customers this way who cannot wait for the 8.0 release.. I am using the "actual" 2.0 from GH as the core code. I've seen a few things that caused me some small issues and will post them as issues on the 20_for_754.
