### ISSUE TITLE
2.0 - Grouped List and List Actions appear to be incomparable w/each other

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#44]
You can build a List view as a normal list and add in List Actions - but attempting to have a grouped list w/List Actions "fails". Firebug pops a "typeError: _2df is null" (in dojo.js line 15)

If I "rip out"  all list actions from the list.js it will display.. but no list actions available :-(

FYI - tested it using Account list.js - latest 2.0 SalesLogix and sdk from GH.

**Comment by wskidmore** [comment]
I see the problem, the invisible action toolbar node is not added to the GroupedList widgetTemplate (since it overrides the List template to add the content node as a div for groups).

Will push up a fix with a defect id shortly.

**Comment by rjledger** [comment]
AH!... I knew you would have a quick and clean answer!
It's these kind of things that help us (people like me ;-) to better understand just what the internal parts and pieces are and how they relate.

Really appreciate the support!
FYI - my "test" environment is actually our production 7.5.4 Saleslogix system.. (as well as a vm that has a true test/eval setup)

**Comment by wskidmore** [comment]
Fixed:
https://github.com/Sage/argos-sdk/commit/1fb629fedb16a3e3592540e74a269de3e49ab10b

This is not an issue with v3 because GroupedList doesn't override List markup anymore.

**Comment by rjledger** [comment]
Put in your "fix" and tested just fine in my test/dev as well as production environment. - FYI - I am testing using the 20_for_754 "wedge".

Ques.. so do we still have the ability to do grouped list in v3?
